[package]
name = "yesterday_weather"
version = "0.1.0"
authors = ["Chris Holcombe <xfactor973@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
clap = "*"
chrono = { version="*"}
forecast = "~2.0"
reqwest = "~0.9"
rusqlite = "*"
serde_json = "~1.0"